name: Build and test rippled
on:
  workflow_run:
    workflows: [ "Download rippled dependencies" ]
    types:
      - completed

# The files starting with "build-" are all interdependent.
# If any significant changes are made, be sure to update them
# to keep them in sync.

env:
  CMAKE_EXTRA_ARGS: "-Dwerr=ON -Dwextra=ON"
  NINJA_BUILD: true
  CACHE_DIR: ${{ github.workspace }}/_cache
  NIH_CACHE_ROOT: ${{ github.workspace }}/_cache/nih_c
  PARALLEL_TESTS: true
  USE_CCACHE: true
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_NOHASHDIR: true
  CCACHE_DIR: ${{ github.workspace }}/_cache/ccache

jobs:
  linux_everything_else:
    name: Linux
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-18.04
    timeout-minutes: 720
    outputs:
      cmakeconfig: ${{ steps.cachekeys.outputs.cmakeconfig }}
      headers: ${{ steps.cachekeys.outputs.headers }}
      source: ${{ steps.cachekeys.outputs.source }}
    strategy:
      fail-fast: false
      matrix:
        # Current travis: gcc-8 clang-8 gcc-9 clang-9
        # testing image (2020-01-08) has clang 7,8,9 & gcc 6,7,8,9
        # packaging image (2944b78d22db) has clang 10 & gcc 8
        CC: [ "gcc-8", "gcc-9", "clang-8", "clang-9", "clang-10" ]
        BUILD_TYPE: [ Debug, Release ]
        unity: [ "OFF", "ON" ]
        image: [ "rippled-ci-builder:2020-01-08", "rippled-ci-builder:2944b78d22db" ]
        name: [ "base" ]
        exclude:
            # The 2020-01-08 image doesn't have clang-10
            - image: "rippled-ci-builder:2020-01-08"
              CC: "clang-10"
            # Both images have gcc-8, but Coverage build needs 2020-01-08
            # so use that one on all gcc-8 builds, so the cache will
            # always work
            - image: "rippled-ci-builder:2944b78d22db"
              CC: "gcc-8"
            # The 2944b78d22db image doesn't have the other compilers, so
            # use 202-01-08
            - image: "rippled-ci-builder:2944b78d22db"
              CC: "gcc-9"
            - image: "rippled-ci-builder:2944b78d22db"
              CC: "clang-8"
            - image: "rippled-ci-builder:2944b78d22db"
              CC: "clang-9"
            # These combos are covered by the individual builds
            - CC: "clang-8"
              unity: "ON"
            - CC: "gcc-8"
              unity: "ON"
        include:
            # Special cases which add to or override the cases in the
            # matrix.
            #
            # gcc Release unity builds run out of memory, so build smaller
            # unity files.
            - CC: "gcc-9"
              BUILD_TYPE: Release
              unity: "ON"
              CMAKE_ADD: "-DCMAKE_UNITY_BUILD_BATCH_SIZE=7"
    container:
      image: rippleci/${{ matrix.image }}
    env:
      CC: ${{ matrix.CC }}
      BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      CMAKE_ADD: "-Dunity=${{ matrix.unity }} ${{ matrix.CMAKE_ADD }}"
      NUM_PROCESSORS: ${{ matrix.NUM_PROCESSORS }}
      # Try to ensure at least 1Gb of space is free to run tests
      MINTESTAVAIL: 1000000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Build cache keys
        id: cachekeys
        shell: bash
        run: |
          echo "::set-output name=cmakeconfig::${{ hashfiles('CMakeFiles.txt', 'Builds/CMake/**') }}"
          echo "::set-output name=headers::${{ hashfiles('src/**/*.h', 'src/**/*.hpp', 'src/**/*.ipp') }}"
          echo "::set-output name=source::${{ hashfiles('src/**', '!src/**/*.md', '!src/**/*.uml', '!src/**/*.png', '!src/**/*.php') }}"
      - name: Cache
        continue-on-error: true
        uses: actions/cache@v2
        # The cache key is built on the following in order
        # 1) OS.
        # 2) The hash of all the CMake config files.
        # 3) The build compiler
        # 4) The build type
        # 5) The build unity setting
        # 6) The build custom name.
        # 7) The hash of all the header files under the source dir.
        # 8) The hash of all the code files under the source dir.
        # When restoring, if the matching cache is not found, search for a usable
        # cache by chopping pieces off the end of the cache key until a match is
        # found, with special cases for a "base" build, and the NIH built in the
        # previous job
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}-${{ steps.cachekeys.outputs.cmakeconfig }}-${{ matrix.CC }}-${{ matrix.BUILD_TYPE }}-${{ matrix.UNITY }}-${{ matrix.name }}-${{ steps.cachekeys.outputs.headers }}-${{ steps.cachekeys.outputs.source }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.cachekeys.outputs.cmakeconfig }}-${{ matrix.CC }}-${{ matrix.BUILD_TYPE }}-${{ matrix.UNITY }}-${{ matrix.name }}-${{ steps.cachekeys.outputs.headers }}
            ${{ runner.os }}-${{ steps.cachekeys.outputs.cmakeconfig }}-${{ matrix.CC }}-${{ matrix.BUILD_TYPE }}-${{ matrix.UNITY }}-${{ matrix.name }}
            ${{ runner.os }}-${{ steps.cachekeys.outputs.cmakeconfig }}-${{ matrix.image }}-nih
      - name: Dump environment
        run: |
          env
          set | grep =
      - name: Reset ccache stats
        run: |
            if ! type -a ccache
            then
              apt install ccache
            fi
            ccache -s
            # Reset the stats so only this build counts
            ccache -z
      - name: Disk space before
        shell: bash
        run: |
          df -h
          du -sh ${CACHE_DIR}
          du -sh ${CCACHE_DIR} || true
          find ${NIH_CACHE_ROOT} -maxdepth 2 \( -iname src -prune -o -type d -exec du -sh {} \; \)
      - name: Build and test
        uses: ./.github/actions/build-action
        with:
          image: ${{ matrix.image }}
      - name: Disk space after
        shell: bash
        if: always()
        run: |
          df -h
          du -sh ${CACHE_DIR}
          du -sh ${CCACHE_DIR} || true
          find ${NIH_CACHE_ROOT} -maxdepth 2 \( -iname src -prune -o -type d -exec du -sh {} \; \)
      - name: Post-run ccache stats
        shell: bash
        run: ccache -s
      - name: Debug output artifacts
        if: always()
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: debug-output ${{ matrix.name }} ${{ matrix.CC }} ${{ matrix.BUILD_TYPE }} unity=${{ matrix.UNITY }}
          retention-days: 7
          if-no-files-found: ignore
          path: |
            build/**/CMakeOutput.log
            build/**/CMakeError.log
      - name: rippled executable artifact
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: rippled ${{ matrix.name }} ${{ matrix.CC }} ${{ matrix.BUILD_TYPE }} unity=${{ matrix.UNITY }}
          retention-days: 7
          if-no-files-found: ignore
          path: |
            build/**/rippled
            !build/**/_INSTALLED_/**