name: Build and test rippled
on: [push, pull_request]

env:
  CMAKE_EXTRA_ARGS: "-Dwerr=ON -Dwextra=ON"
  NINJA_BUILD: true
  CACHE_DIR: ${{ github.workspace }}/_cache
  NIH_CACHE_ROOT: ${{ github.workspace }}/_cache/nih_c
  PARALLEL_TESTS: true
  USE_CCACHE: true
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_NOHASHDIR: true
  CCACHE_DIR: ${{ github.workspace }}/_cache/ccache

jobs:
  linux1:
    name: Linux 1
    runs-on: ubuntu-18.04
    timeout-minutes: 720
    # if: commit_message !~ /travis_run_/ OR commit_message =~ /travis_run_linux/
    strategy:
      fail-fast: false
      matrix:
        # Current travis: gcc-8 clang-8 gcc-9 clang-9
        # docker image has clang 7,8,9 & gcc 6,7,8,9
        BUILD: [ "matrix" ]
        CC: [ "gcc-9", "clang-8" , "clang-9" , "gcc-8" ]
        BUILD_TYPE: [ Debug, Release ]
        unity: [ "unity=OFF", "unity=ON" ]
        #canfail: [ false ]
        #exclude:
        #    - CC: "clang-8"
        #    - CC: "clang-9"
        #    - CC: "gcc-8"
        #    - BUILD_TYPE: "Debug"
        #    - BUILD: ""
        include:
            # Special cases which add to or override the cases in the
            # matrix.
            #
            # gcc-9 Release unity runs out of memory, so build smaller
            # unity files.
            - CC: "gcc-9"
              BUILD_TYPE: "Release"
              unity: "unity=ON"
              CMAKE_ADD: "-DCMAKE_UNITY_BUILD_BATCH_SIZE=7"
              BUILD: "gcc-9 Release unity"
#            # Reporting mode
#            - CMAKE_ADD: "-Dreporting=ON"
#              CC: "clang-8"
#              BUILD_TYPE: "Debug"
#              BUILD: "Reporting, clang-8, debug"
#            # Coverage builds
#            - CMAKE_ADD: "-Dcoverage=ON"
#              CC: "gcc-8"
#              BUILD_TYPE: "Debug"
#              TARGET: coverage_report
#              SKIP_TESTS: true
#              BUILD: "Coverage, gcc-8"
#            - CMAKE_ADD: "-Dcoverage=ON"
#              CC: "clang-8"
#              BUILD_TYPE: "Debug"
#              TARGET: coverage_report
#              SKIP_TESTS: true
#              BUILD: "Coverage, clang-8"
#            # Manual tests
#            - MANUAL_TESTS: true
#              CC: "gcc-8"
#              BUILD_TYPE: Debug
#              BUILD: "Manual tests, gcc-8, debug"
#            - MANUAL_TESTS: true
#              CC: "gcc-8"
#              BUILD_TEST: "Release"
#              CMAKE_ADD: "-Dassert=ON -Dunity=OFF"
#              BUILD: "Manual tests, gcc-8, release"
#            # asan
#            - CMAKE_ADD: "-Dsan=address"
#              CC: "clang-8"
#              BUILD_TYPE: Release
#              ASAN_OPTIONS: "print_stats=true:atexit=true"
#              PARALLEL_TESTS: false
#              BUILD: "asan, clang-8"
#            # ubsan
#            - CMAKE_ADD: "-Dsan=undefined"
#              CC: "clang-8"
#              BUILD_TYPE: Release
#              UBSAN_OPTIONS: "print_stacktrace=1:report_error_type=1"
#              PARALLEL_TESTS: false
#              BUILD: "ubsan, clang-8"
#            # tsan
#            # current tsan failure *might* be related to:
#            # https://github.com/google/sanitizers/issues/1104
#            #  but we can't get it to run, so leave it disabled for now
#            - CMAKE_ADD: "-Dsan=thread"
#              CC: "clang-8"
#              BUILD: "tsan, clang-8"
#              BUILD_TYPE: "Release"
#              TSAN_OPTIONS: "history_size=3 external_symbolizer_path=/usr/bin/llvm-symbolizer verbosity=1"
#              PARALLEL_TESTS: false
#            # dynamic lib builds
#            - CMAKE_ADD: "-Dstatic=OFF"
#              CC: "gcc-8"
#              BUILD: "non-static, gcc-8"
#              BUILD_TYPE: Debug
#            - CMAKE_ADD: "-Dstatic=OFF -DBUILD_SHARED_LIBS=ON"
#              CC: "gcc-8"
#              BUILD: "non-static + BUILD_SHARED_LIBS, gcc-8"
#              BUILD_TYPE: Debug
#            # makefile
#            - NINJA_BUILD: false
#              CC: "gcc-8"
#              BUILD: "makefile generator, gcc-8"
#              BUILD_TYPE: Debug
#            # verify build with min version of cmake
#            - CMAKE_EXE: /opt/local/cmake-3.9/bin/cmake
#              CC: "gcc-8"
#              BUILD: "min cmake version"
#              BUILD_TYPE: Debug
#              SKIP_TESTS: true
#            # validator keys project as subproj of rippled
#            - TARGET: validator-keys
#              CC: "gcc-8"
#              BUILD: "validator-keys"
#              BUILD_TYPE: Debug
#              CMAKE_ADD: "-Dvalidator_keys=ON"
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error
    continue-on-error: ${{ matrix.canfail }}
    container:
      image: "rippleci/rippled-ci-builder:2020-01-08"
    env:
      BUILD: ${{ matrix.BUILD }}
      CC: ${{ matrix.CC }}
      BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      CMAKE_ADD: "-D${{ matrix.unity }} ${{ matrix.CMAKE_ADD }}"
      NUM_PROCESSORS: ${{ matrix.NUM_PROCESSORS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cache
        continue-on-error: true
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key:  ${{ runner.os }}-build-${{ hashfiles('**/CMakeFiles.txt', '**/Builds/CMake/*', '**/Builds/CMake/deps/*') }}-${{ matrix.CC }}-${{ matrix.BUILD_TYPE }}-${{ matrix.UNITY }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashfiles('**/CMakeFiles.txt', '**/Builds/CMake/*', '**/Builds/CMake/deps/*') }}
      - name: Dump-environment
        run: |
          env
          set | grep =
      - name: ccache stats before
        run: ccache -s
      - name: Build and test
        shell: bash
        run: |
          export CXX=${CC/gcc/g++}
          export CXX=${CXX/clang/clang++}
          export NUM_PROCESSORS=${NUM_PROCESSORS:-$( nproc )}
          echo NUM_PROCESSORS is ${NUM_PROCESSORS}
          # Override environment variables that don't work smoothly
          # using env:
          if [[ "${{ matrix.PARALLEL_TESTS }}" != "" ]]; then export PARALLEL_TESTS="${{ matrix.PARALLEL_TESTS }}" ; fi
          if [[ "${{ matrix.TARGET }}" != "" ]]; then export TARGET="${{ matrix.TARGET }}" ; fi
          if [[ "${{ matrix.SKIP_TESTS }}" != "" ]]; then export SKIP_TESTS="${{ matrix.SKIP_TESTS }}" ; fi
          if [[ "${{ matrix.MANUAL_TESTS }}" != "" ]]; then export MANUAL_TESTS="${{ matrix.MANUAL_TESTS }}" ; fi
          if [[ "${{ matrix.ASAN_OPTIONS }}" != "" ]]; then export ASAN_OPTIONS="${{ matrix.ASAN_OPTIONS }}" ; fi
          if [[ "${{ matrix.UBSAN_OPTIONS }}" != "" ]]; then export UBSAN_OPTIONS="${{ matrix.UBSAN_OPTIONS }}" ; fi
          if [[ "${{ matrix.TSAN_OPTIONS }}" != "" ]]; then export TSAN_OPTIONS="${{ matrix.TSAN_OPTIONS }}" ; fi
          if [[ "${{ matrix.NINJA_BUILD }}" != "" ]]; then export NINJA_BUILD="${{ matrix.NINJA_BUILD }}" ; fi
          if [[ "${{ matrix.CMAKE_EXE }}" != "" ]]; then export CMAKE_EXE="${{ matrix.CMAKE_EXE }}" ; fi
          if [ "${CMAKE_ADD}" != "" ] ; then export CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} ${CMAKE_ADD}"; fi
          # Do the build
          bin/ci/ubuntu/build-and-test.sh
      - name: ccache stats after
        run: ccache -s
      - name: Debug output
        if: always()
        shell: bash
        run: if [ -e build ] ; then find build \( -name CMakeOutput.log -o -name CMakeError.log \) -ls -exec cat {} \; ; fi
  linux2:
    name: Linux 2
    runs-on: ubuntu-18.04
    timeout-minutes: 720
    # if: commit_message !~ /travis_run_/ OR commit_message =~ /travis_run_linux/
    strategy:
      fail-fast: false
      matrix:
        # Current travis: gcc-8 clang-8 gcc-9 clang-9
        # docker image has clang 10 & gcc 7,8
        CC: [ "gcc-8", "clang-10" ]
        BUILD_TYPE: [ Debug, Release ]
        unity: [ "unity=OFF", "unity=ON" ]
        canfail: [ false ]
        #exclude:
        #  - CC: "clang-10"
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error
    continue-on-error: ${{ matrix.canfail }}
    container:
      image: "rippleci/rippled-ci-builder:2944b78d22db"
    env:
      CC: ${{ matrix.CC }}
      BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      CMAKE_ADD: "-D${{ matrix.unity }} -DBoost_NO_BOOST_CMAKE=ON ${{ matrix.CMAKE_ADD }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cache
        continue-on-error: true
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key:  ${{ runner.os }}-build-${{ hashfiles('**/CMakeFiles.txt', '**/Builds/CMake/*', '**/Builds/CMake/deps/*') }}-${{ matrix.CC }}-${{ matrix.BUILD_TYPE }}-${{ matrix.UNITY }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashfiles('**/CMakeFiles.txt', '**/Builds/CMake/*', '**/Builds/CMake/deps/*') }}
      - name: Dump-environment
        run: |
          env
          set | grep =
      - name: ccache install and stats before
        run: |
          apt install ccache
          ccache -s
#      - name: Configure
#        shell: bash
#        run: |
#          export CXX=${CC/gcc/g++}
#          export CXX=${CXX/clang/clang++}
#          if [ "${CMAKE_ADD}" != "" ] ; then export CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} ${CMAKE_ADD}"; fi
#          cmake --version
#          ${CC} --version
#          ${CXX} --version
#          mkdir build
#          cd build
#          cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${CMAKE_EXTRA_ARGS} ..
#      - name: Build rippled
#        run: |
#          echo Building with $( nproc ) jobs
#          cmake --build build --target rippled --config ${{ env.BUILD_TYPE }} -j $( nproc )
#      - name: Run tests
#        run: |
#          echo Running $( nproc ) parallel tests
#          build/rippled --unittest --unittest-jobs=$( nproc ) --quiet --unittest-log
      - name: Build and test
        shell: bash
        run: |
          export CXX=${CC/gcc/g++}
          export CXX=${CXX/clang/clang++}
          export NUM_PROCESSORS=${NUM_PROCESSORS:-$( nproc )}
          echo NUM_PROCESSORS is ${NUM_PROCESSORS}
          if [ "${CMAKE_ADD}" != "" ] ; then export CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} ${CMAKE_ADD}"; fi
          bin/ci/ubuntu/build-and-test.sh
      - name: ccache stats after
        run: ccache -s
      - name: Debug output
        if: always()
        shell: bash
        run: if [ -e build ] ; then find build \( -name CMakeOutput.log -o -name CMakeError.log \) -ls -exec cat {} \; ; fi
