name: macos
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    strategy:
      matrix:
        platform:
          - macos
        generator:
          - Ninja
        configuration:
          - Release
    runs-on: [self-hosted, macOS]
    env:
      # The `build` action requires these variables.
      build_dir: .build
      NUM_PROCESSORS: 12
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: merge with base
        if: github.base_ref != ''
        shell: bash
        run: |
          # If there are any conflicts, leave them, so the build will
          # fail. However, Github will probably prevent the job from
          # running at all.
          git log --oneline
          git merge --no-commit --no-edit -v \
            ${{ github.event.pull_request.base.sha }}
          git diff || true
      - name: install Ninja
        if: matrix.generator == 'Ninja'
        run: brew install ninja
      - name: check environment
        run: |
          echo ${PATH} | tr ':' '\n'
          python --version
          conan --version
          cmake --version
          env | sort
      - name: build
        uses: ./.github/actions/build
        with:
          generator: ${{ matrix.generator }}
          configuration: ${{ matrix.configuration }}
      - name: test
        run: |
          ${build_dir}/rippled --unittest
