name: "Windows build, general"
on: [push, pull_request]

# The files starting with "build-" are all interdependent.
# If any significant changes are made, be sure to update them
# to keep them in sync.

env:
  CMAKE_EXTRA_ARGS: "-Dwerr=ON -Dwextra=ON"
  NINJA_BUILD: true
  CACHE_DIR: ${{ github.workspace }}\_cache
  NIH_CACHE_ROOT: ${{ github.workspace }}\_cache\nih_c
  PARALLEL_TESTS: true
  USE_CCACHE: true
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_NOHASHDIR: true
  CCACHE_DIR: ${{ github.workspace }}\_cache\ccache
  VCVARS_VER: 14.1
  BOOST_TOOLSET: msvc-14.1
  BOOST_URL: 'https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2'
  # BOOST_URL: 'https://dl.bintray.com/boostorg/release/1.75.0/binaries/boost_1_75_0-msvc-14.1-64.exe'
  # Alternate dowload location
  BOOST_URL2: 'https://downloads.sourceforge.net/project/boost/boost/1.75.0/boost_1_75_0.tar.bz2?r=&amp;ts=1594393912&amp;use_mirror=newcontinuum'
  BOOST_ROOT: ${{ github.workspace }}\_cache\boost_1_75_0
  # Travis downloader doesn't seem to have updated certs. Using this option
  # introduces obvious security risks, but they're Travis's risks.
  # Note that this option is only used if the "normal" build fails.
  #BOOST_WGET_OPTIONS: '--no-check-certificate'
  CMAKE_ADD: |
    -DCMAKE_PREFIX_PATH=${BOOST_ROOT}\_INSTALLED_
    -DBOOST_ROOT=${BOOST_ROOT}\_INSTALLED_
    -DBoost_ROOT=${BOOST_ROOT}\_INSTALLED_
    -DBoost_DIR=${BOOST_ROOT}\_INSTALLED_\lib\cmake\Boost-1.75.0
    -DBoost_COMPILER=vc141
    -DCMAKE_VERBOSE_MAKEFILE=ON
    -DCMAKE_TOOLCHAIN_FILE=${VCPKG_DIR}\scripts\buildsystems\vcpkg.cmake
    -DVCPKG_TARGET_TRIPLET=x64-windows-static
  VCPKG_DIR: '/c/vcpkg'
  VCPKG_INSTALL_DIR: ${{ github.workspace }}\_cache\vcpkg\installed
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}\_cache\vcpkg\binary
  VCPKG_DOWNLOADS: ${{ github.workspace }}\_cache\vcpkg\download
  VCPKG_DEFAULT_TRIPLET: "x64-windows-static"
  # MSVC_DIR: '/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise'
  CC: cl.exe
  CXX: cl.exe
  srcdir: ${{ github.workspace }}\rippled
  builddir: ${{ github.workspace }}\rippled\build\ms
  invalidate_cache: ${{ contains(github.event.head_commit.message, 'ci_invalidate_cache') }}

jobs:
  windows_cache:
    name: Seed windows cache
    # The NIH setup puts all the dependency source code in a single,
    # shared directory. Run cmake across all of the compiler combos,
    # then put all the NIH code in the cache. This accomplishes:
    # 1) This cache will be as small as possible, since the source is
    #    not duplicated.
    # 2) This cache will be available to all builds, so they don't all
    #    have to separately download, for example, NuDB.
    # 3) Unity does not affect the NIH cache, so those two builds can
    #    share this cache.
    # 4) The time to download is not wasted if a build fails, even
    #    though a failed build will not push a cache.
    # The one downside is that not all compilers are available on all
    # docker images, so there will be one cache per image.
    runs-on: windows-latest
    timeout-minutes: 720
    if: ${{ !contains(github.event.head_commit.message, 'ci_run_') || contains(github.event.head_commit.message, 'ci_run_win') }}
    outputs:
      cachesuffix: ${{ steps.cachekeys.outputs.suffix }}
      cmakeconfig: ${{ steps.cachekeys.outputs.cmakeconfig }}
      headers: ${{ steps.cachekeys.outputs.headers }}
      source: ${{ steps.cachekeys.outputs.source }}
      NUM_PROCESSORS: ${{ steps.cachekeys.outputs.NUM_PROCESSORS }}
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    vsupdate: [ 'vs_installer.exe', 'vs_installershell.exe' ]
    #    vsparam: [ '', '--updateFromVS' ]
    steps:
      - name: Cancel Previous Runs
        if: ${{ !contains(github.event.head_commit.message, 'ci_no_cancel') }}
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: rippled
      - name: Build parameters
        id: cachekeys
        shell: bash
        run: |
          if [[ "${invalidate_cache}" == "true" ]]
          then
            echo "::set-output name=suffix::-$( date +%s )"
          fi
          echo "::set-output name=cmakeconfig::${{ hashfiles('rippled/CMakeFiles.txt', 'rippled/Builds/CMake/**') }}"
          echo "::set-output name=headers::${{ hashfiles('rippled/src/**/*.h', 'rippled/src/**/*.hpp', 'rippled/src/**/*.ipp') }}"
          echo "::set-output name=source::${{ hashfiles('rippled/src/**', '!rippled/src/**/*.md', '!rippled/src/**/*.uml', '!rippled/src/**/*.png', '!rippled/src/**/*.php') }}"
          export NUM_PROCESSORS=${NUM_PROCESSORS:-$(nproc)}
          echo "NUM PROC is ${NUM_PROCESSORS}"
          echo "::set-output name=NUM_PROCESSORS::${NUM_PROCESSORS}"
      - name: Cache
        id: cache
        continue-on-error: true
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}-${{ steps.cachekeys.outputs.cmakeconfig }}-nih${{ steps.cachekeys.outputs.suffix }}
      - name: Dump environment
        shell: bash
        run: |
          env
          set | grep =
      - name: Install build tools
        if: ${{ ! steps.cache.outputs.cache-hit }}
        shell: bash
        env:
          NUM_PROCESSORS: ${{ steps.cachekeys.outputs.NUM_PROCESSORS }}
        run: |
            set -x

            mkdir -pv ${CACHE_DIR} ${CCACHE_DIR} ${NIH_CACHE_ROOT} \
              ${VCPKG_DIR} ${VCPKG_DEFAULT_BINARY_CACHE} ${VCPKG_DOWNLOADS}

            if false
            then
                vswhere -all

                /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/Installer/${{ matrix.vsupdate }} \
                   update --channelId  VisualStudio.16.Release \
                   --productID Microsoft.VisualStudio.Product.Community --quiet \
                   --force ${{ matrix.vsparam }}

                /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/Installer/${{ matrix.vsupdate }} \
                   export --channelId  VisualStudio.16.Release \
                   --productID Microsoft.VisualStudio.Product.Community --quiet

                find ~ -iname .vsconfig -ls -exec cat {} \; -exec mv -v {} {}.before \;

                /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/Installer/${{ matrix.vsupdate }} \
                   modify --channelId VisualStudio.16.Release \
                   --productID Microsoft.VisualStudio.Product.Enterprise --quiet \
                   --includeRecommended \
                   --add "Microsoft.VisualStudio.Component.VC.v141.x86.x64" \
                   --add "Microsoft.VisualStudio.Component.VC.v141.ARM64" \
                   --add "Microsoft.Component.MSBuild" \
                   --add "Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

                /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/Installer/${{ matrix.vsupdate }} \
                   export --channelId  VisualStudio.16.Release \
                   --productID Microsoft.VisualStudio.Product.Community --quiet

                find ~ -iname .vsconfig -ls -exec cat {} \; -exec diff {}.before {} \;
            fi

            type -a choco

            choco outdated
            choco list | wc
            choco upgrade cmake.install
            choco install ninja -y
            # choco install visualstudio2017community -y
            # choco install visualstudio2017-workload-vctools -y
            # choco install visualstudio2019buildtools --package-parameters "--allWorkloads --includeRecommended --includeOptional"
            # choco install visualstudio2019-workload-vctools -y

            type -a ninja

      - name: Initialize vcpkg cache
        if: ${{ ! steps.cache.outputs.cache-hit }}
        shell: bash
        env:
          NUM_PROCESSORS: ${{ steps.cachekeys.outputs.NUM_PROCESSORS }}
        run: |
            set -x

            type -a cl.exe || true
            ls -l
            ls -l /
            cd rippled
            . ./bin/sh/setup-msvc.sh
            type -a cl.exe || true

            type -a vcpkg
            ls -l ${VCPKG_DIR}
            mkdir -pv ${VCPKG_DIR}/installed
            vcpkg help || true
            # find ${BOOST_ROOT} -type d

            df -h
            # bin/sh/install-vcpkg.sh openssl
            # bin/sh/install-vcpkg.sh libarchive[lz4]
            # bin/sh/install-vcpkg.sh grpc

            find ${VCPKG_DIR} -mmin -120
            # TBD consider rocksdb via vcpkg if/when we can build with the
            # vcpkg version
            # bin/sh/install-vcpkg.sh rocksdb[snappy,lz4,zlib]
      - name: Download Boost
        if: ${{ ! steps.cache.outputs.cache-hit }}
        # Powershell
        shell: pwsh
        run: |
            $Url = "$env:BOOST_URL"
            (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.tar.bz2")
      - name: Install Boost
        if: ${{ ! steps.cache.outputs.cache-hit }}
        shell: bash
        env:
          BOOST_FILE: ${TEMP}\boost.tar.bz2
        run: |
            set -x

            type -a ninja
            export BOOST_FILE="${TEMP}\boost.tar.bz2"
            ls -l "${BOOST_FILE}"
            ls -l "${CACHE_DIR}" || true

            cd rippled

            . ./bin/sh/setup-msvc.sh

            # Pre-installed boost is going to be deprecated
            # https://github.com/actions/virtual-environments/issues/2667
            ./Builds/containers/shared/install_boost.sh
      - name: Initialize cmake cache
        if: ${{ ! steps.cache.outputs.cache-hit }}
        shell: bash
        env:
          NUM_PROCESSORS: ${{ steps.cachekeys.outputs.NUM_PROCESSORS }}
        run: |
            set -x

            type -a ninja || true
            choco list | wc
            type -a ninja
            cd rippled
            . ./bin/sh/setup-msvc.sh

            # Download the NIH items
            mkdir -p $builddir && cd $builddir
            if [ "${CMAKE_ADD}" != "" ] ; then export CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} $( eval echo ${CMAKE_ADD} )"; fi
            cmake -G Ninja ${CMAKE_EXTRA_ARGS} -DCMAKE_BLD_CONFIG=${BLD_CONFIG} ${srcdir}

            grep -i -e vcpkg -e _cache CMakeCache.txt

            du -sh ${CACHE_DIR}
            du -sh ${CCACHE_DIR} || true
            find ${NIH_CACHE_ROOT} -maxdepth 2 \( -iname src -prune -o -type d -exec du -sh {} \; \)
      - name: Debug output
        if: ${{ ! steps.cache.outputs.cache-hit || failure() }}
        shell: bash
        continue-on-error: true
        run: |
          time df -h
          if [ -e build ] ; then find build \( -name CMakeOutput.log -o -name CMakeError.log \) -ls -exec cat {} \; ; fi
      - name: Debug output artifacts
        if: ${{ ! steps.cache.outputs.cache-hit || failure() }}
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: debug-output NIH ${{ matrix.ninja_ccs }}
          retention-days: 7
          if-no-files-found: ignore
          path: |
            build/**/CMakeOutput.log
            build/**/CMakeError.log
  windows_everything_else:
    name: Windows
    needs: windows_cache
    runs-on: windows-latest
    timeout-minutes: 720
    strategy:
      fail-fast: false
      matrix:
        BLD_CONFIG: [ Debug ]
    env:
      BLD_CONFIG: ${{ matrix.BLD_CONFIG }}
      NUM_PROCESSORS: ${{ needs.windows_cache.outputs.NUM_PROCESSORS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: rippled
      - name: Cache
        continue-on-error: true
        uses: actions/cache@v2
        # The cache key is built on the following in order
        # 1) OS.
        # 2) The hash of all the CMake config files.
        # 3) The build type
        # 4) The build custom name
        # 5) The hash of all the header files under the source dir.
        # 6) The hash of all the code files under the source dir.
        # 7) The cache invalidation suffix, if any
        # When restoring, if the matching cache is not found, search for a
        # usable cache by chopping pieces off the end of the cache key,
        # except for the invalidation suffix until a match is found, with
        # a special case for the NIH built in the previous job.
        # The invalidation suffix is left on all of the restore keys except
        # the NIH to ensure a partial match is _not_ found, and to force the
        # NIH cache to be used.
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}-${{ needs.windows_cache.outputs.cmakeconfig }}-${{ matrix.BLD_CONFIG }}-${{ matrix.name }}-${{ needs.windows_cache.outputs.headers }}-${{ needs.windows_cache.outputs.source }}${{needs.windows_cache.outputs.suffix}}
          restore-keys: |
            ${{ runner.os }}-${{ needs.windows_cache.outputs.cmakeconfig }}-${{ matrix.BLD_CONFIG }}-${{ matrix.name }}-${{ needs.windows_cache.outputs.headers }}${{needs.windows_cache.outputs.suffix}}
            ${{ runner.os }}-${{ needs.windows_cache.outputs.cmakeconfig }}-${{ matrix.BLD_CONFIG }}-${{ matrix.name }}${{needs.windows_cache.outputs.suffix}}
            ${{ runner.os }}-${{ needs.windows_cache.outputs.cmakeconfig }}-nih
      - name: Dump environment
        shell: bash
        run: |
          env
          set | grep =
      - name: Reset ccache stats
        if: false
        shell: bash
        run: |
            if ! type -a ccache
            then
              apt install ccache
            fi
            ccache -s
            # Reset the stats so only this build counts
            ccache -z
      - name: Disk space before
        shell: bash
        run: |
          df -h
          du -sh ${CACHE_DIR}
          du -sh ${CCACHE_DIR} || true
          find ${NIH_CACHE_ROOT} -maxdepth 2 \( -iname src -prune -o \
            -type d -exec du -sh {} \; \) || true
      - name: Build and test
        shell: bash
        run: |
            set -x
            df -h
            # Make sure we can see the installed packages
            bin/sh/install-vcpkg.sh
            cd rippled
            . ./bin/sh/setup-msvc.sh
            mkdir -p $builddir && cd $builddir
            if [ "${CMAKE_ADD}" != "" ] ; then export CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} $( eval echo ${CMAKE_ADD} )"; fi
            cmake -G Ninja ${CMAKE_EXTRA_ARGS} -DCMAKE_BLD_CONFIG=${BLD_CONFIG} ${srcdir}
            cmake --build . --parallel --verbose
            # override num procs to force fewer unit test jobs
            # export NUM_PROCESSORS=2
            ./rippled.exe --unittest --quiet --unittest-log --unittest-jobs ${NUM_PROCESSORS}
      - name: Disk space after
        shell: bash
        if: always()
        run: |
          df -h
          du -sh ${CACHE_DIR}
          du -sh ${CCACHE_DIR} || true
          find ${NIH_CACHE_ROOT} -maxdepth 2 \( -iname src -prune -o \
            -type d -exec du -sh {} \; \) || true
      - name: Post-run ccache stats
        if: false
        shell: bash
        run: ccache -s
      - name: Debug output artifacts
        if: ${{ false && always() }}
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: debug-output ${{ matrix.name }} ${{ matrix.CC }} ${{ matrix.BLD_CONFIG }} unity=${{ matrix.UNITY }}
          retention-days: 7
          if-no-files-found: ignore
          path: |
            build/**/CMakeOutput.log
            build/**/CMakeError.log
      - name: rippled executable artifact
        uses: actions/upload-artifact@v2
        if: false
        continue-on-error: true
        with:
          name: rippled ${{ matrix.name }} ${{ matrix.CC }} ${{ matrix.BLD_CONFIG }} unity=${{ matrix.UNITY }}
          retention-days: 7
          if-no-files-found: ignore
          path: |
            build/**/rippled
            !build/**/_INSTALLED_/**